name: Test

on: [pull_request, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"
      - name: "setup node"

        uses: "actions/setup-node@v4"
        with:
          node-version: 20
      - name: Install and Build
        run: pnpm install && pnpm run build
      - name: Get timestamp and short SHA
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Website-${{ steps.timestamp.outputs.short_sha }}
          path: build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
